server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

spring:
  rabbitmq:
    host: rabbitmq
    username: bingbing
    password: bingbing
  datasource:
    url: jdbc:mysql://localhost:3306/bmd?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: konsung_!@#$
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
  jpa:
    show-sql: true
